export const USER_API = '/user/api/v1'
export const OPENURL_API = '/service/url/openurl/v1'
export const MODEL_API = '/use/model/api/v1'
export const WORKFLOW_API = '/workflow/api'
export const SERVICE_API = '/service/api/v1'
export const DATACENTER_API = '/datacenter/api/v1'
export const KNOWLEDGE_API = '/konwledgeServe/v1'