// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package knowledgebase_permission_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KnowledgeBasePermissionServiceClient is the client API for KnowledgeBasePermissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeBasePermissionServiceClient interface {
	// 查询知识库用户权限
	SelectKnowledgeUserPermission(ctx context.Context, in *KnowledgeUserPermissionReq, opts ...grpc.CallOption) (*KnowledgeUserPermissionResp, error)
	// 校验知识库用户权限,此组织下的userId 需要拥有的权限大于等于 permissionType
	CheckKnowledgeUserPermission(ctx context.Context, in *CheckKnowledgeUserPermissionReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 增加知识库用户
	AddKnowledgeUser(ctx context.Context, in *AddKnowledgeUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 修改知识库用户
	EditKnowledgeUser(ctx context.Context, in *EditKnowledgeUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除知识库用户
	DeleteKnowledgeUser(ctx context.Context, in *DeleteKnowledgeUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 转让知识库管理员权限
	TransferKnowledgeAdminUser(ctx context.Context, in *TransferKnowledgeAdminUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type knowledgeBasePermissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeBasePermissionServiceClient(cc grpc.ClientConnInterface) KnowledgeBasePermissionServiceClient {
	return &knowledgeBasePermissionServiceClient{cc}
}

func (c *knowledgeBasePermissionServiceClient) SelectKnowledgeUserPermission(ctx context.Context, in *KnowledgeUserPermissionReq, opts ...grpc.CallOption) (*KnowledgeUserPermissionResp, error) {
	out := new(KnowledgeUserPermissionResp)
	err := c.cc.Invoke(ctx, "/knowledgebase_permission_service.KnowledgeBasePermissionService/SelectKnowledgeUserPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBasePermissionServiceClient) CheckKnowledgeUserPermission(ctx context.Context, in *CheckKnowledgeUserPermissionReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/knowledgebase_permission_service.KnowledgeBasePermissionService/CheckKnowledgeUserPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBasePermissionServiceClient) AddKnowledgeUser(ctx context.Context, in *AddKnowledgeUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/knowledgebase_permission_service.KnowledgeBasePermissionService/AddKnowledgeUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBasePermissionServiceClient) EditKnowledgeUser(ctx context.Context, in *EditKnowledgeUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/knowledgebase_permission_service.KnowledgeBasePermissionService/EditKnowledgeUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBasePermissionServiceClient) DeleteKnowledgeUser(ctx context.Context, in *DeleteKnowledgeUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/knowledgebase_permission_service.KnowledgeBasePermissionService/DeleteKnowledgeUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBasePermissionServiceClient) TransferKnowledgeAdminUser(ctx context.Context, in *TransferKnowledgeAdminUserReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/knowledgebase_permission_service.KnowledgeBasePermissionService/TransferKnowledgeAdminUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeBasePermissionServiceServer is the server API for KnowledgeBasePermissionService service.
// All implementations must embed UnimplementedKnowledgeBasePermissionServiceServer
// for forward compatibility
type KnowledgeBasePermissionServiceServer interface {
	// 查询知识库用户权限
	SelectKnowledgeUserPermission(context.Context, *KnowledgeUserPermissionReq) (*KnowledgeUserPermissionResp, error)
	// 校验知识库用户权限,此组织下的userId 需要拥有的权限大于等于 permissionType
	CheckKnowledgeUserPermission(context.Context, *CheckKnowledgeUserPermissionReq) (*emptypb.Empty, error)
	// 增加知识库用户
	AddKnowledgeUser(context.Context, *AddKnowledgeUserReq) (*emptypb.Empty, error)
	// 修改知识库用户
	EditKnowledgeUser(context.Context, *EditKnowledgeUserReq) (*emptypb.Empty, error)
	// 删除知识库用户
	DeleteKnowledgeUser(context.Context, *DeleteKnowledgeUserReq) (*emptypb.Empty, error)
	// 转让知识库管理员权限
	TransferKnowledgeAdminUser(context.Context, *TransferKnowledgeAdminUserReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedKnowledgeBasePermissionServiceServer()
}

// UnimplementedKnowledgeBasePermissionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKnowledgeBasePermissionServiceServer struct {
}

func (UnimplementedKnowledgeBasePermissionServiceServer) SelectKnowledgeUserPermission(context.Context, *KnowledgeUserPermissionReq) (*KnowledgeUserPermissionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeUserPermission not implemented")
}
func (UnimplementedKnowledgeBasePermissionServiceServer) CheckKnowledgeUserPermission(context.Context, *CheckKnowledgeUserPermissionReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckKnowledgeUserPermission not implemented")
}
func (UnimplementedKnowledgeBasePermissionServiceServer) AddKnowledgeUser(context.Context, *AddKnowledgeUserReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKnowledgeUser not implemented")
}
func (UnimplementedKnowledgeBasePermissionServiceServer) EditKnowledgeUser(context.Context, *EditKnowledgeUserReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditKnowledgeUser not implemented")
}
func (UnimplementedKnowledgeBasePermissionServiceServer) DeleteKnowledgeUser(context.Context, *DeleteKnowledgeUserReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKnowledgeUser not implemented")
}
func (UnimplementedKnowledgeBasePermissionServiceServer) TransferKnowledgeAdminUser(context.Context, *TransferKnowledgeAdminUserReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferKnowledgeAdminUser not implemented")
}
func (UnimplementedKnowledgeBasePermissionServiceServer) mustEmbedUnimplementedKnowledgeBasePermissionServiceServer() {
}

// UnsafeKnowledgeBasePermissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeBasePermissionServiceServer will
// result in compilation errors.
type UnsafeKnowledgeBasePermissionServiceServer interface {
	mustEmbedUnimplementedKnowledgeBasePermissionServiceServer()
}

func RegisterKnowledgeBasePermissionServiceServer(s grpc.ServiceRegistrar, srv KnowledgeBasePermissionServiceServer) {
	s.RegisterService(&KnowledgeBasePermissionService_ServiceDesc, srv)
}

func _KnowledgeBasePermissionService_SelectKnowledgeUserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeUserPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBasePermissionServiceServer).SelectKnowledgeUserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knowledgebase_permission_service.KnowledgeBasePermissionService/SelectKnowledgeUserPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBasePermissionServiceServer).SelectKnowledgeUserPermission(ctx, req.(*KnowledgeUserPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBasePermissionService_CheckKnowledgeUserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckKnowledgeUserPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBasePermissionServiceServer).CheckKnowledgeUserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knowledgebase_permission_service.KnowledgeBasePermissionService/CheckKnowledgeUserPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBasePermissionServiceServer).CheckKnowledgeUserPermission(ctx, req.(*CheckKnowledgeUserPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBasePermissionService_AddKnowledgeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKnowledgeUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBasePermissionServiceServer).AddKnowledgeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knowledgebase_permission_service.KnowledgeBasePermissionService/AddKnowledgeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBasePermissionServiceServer).AddKnowledgeUser(ctx, req.(*AddKnowledgeUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBasePermissionService_EditKnowledgeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditKnowledgeUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBasePermissionServiceServer).EditKnowledgeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knowledgebase_permission_service.KnowledgeBasePermissionService/EditKnowledgeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBasePermissionServiceServer).EditKnowledgeUser(ctx, req.(*EditKnowledgeUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBasePermissionService_DeleteKnowledgeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBasePermissionServiceServer).DeleteKnowledgeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knowledgebase_permission_service.KnowledgeBasePermissionService/DeleteKnowledgeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBasePermissionServiceServer).DeleteKnowledgeUser(ctx, req.(*DeleteKnowledgeUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBasePermissionService_TransferKnowledgeAdminUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferKnowledgeAdminUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBasePermissionServiceServer).TransferKnowledgeAdminUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knowledgebase_permission_service.KnowledgeBasePermissionService/TransferKnowledgeAdminUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBasePermissionServiceServer).TransferKnowledgeAdminUser(ctx, req.(*TransferKnowledgeAdminUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeBasePermissionService_ServiceDesc is the grpc.ServiceDesc for KnowledgeBasePermissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeBasePermissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledgebase_permission_service.KnowledgeBasePermissionService",
	HandlerType: (*KnowledgeBasePermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectKnowledgeUserPermission",
			Handler:    _KnowledgeBasePermissionService_SelectKnowledgeUserPermission_Handler,
		},
		{
			MethodName: "CheckKnowledgeUserPermission",
			Handler:    _KnowledgeBasePermissionService_CheckKnowledgeUserPermission_Handler,
		},
		{
			MethodName: "AddKnowledgeUser",
			Handler:    _KnowledgeBasePermissionService_AddKnowledgeUser_Handler,
		},
		{
			MethodName: "EditKnowledgeUser",
			Handler:    _KnowledgeBasePermissionService_EditKnowledgeUser_Handler,
		},
		{
			MethodName: "DeleteKnowledgeUser",
			Handler:    _KnowledgeBasePermissionService_DeleteKnowledgeUser_Handler,
		},
		{
			MethodName: "TransferKnowledgeAdminUser",
			Handler:    _KnowledgeBasePermissionService_TransferKnowledgeAdminUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/knowledgebase-permission-service/knowledgebase-permission-service.proto",
}
